# Generated by Django 3.2.4 on 2021-12-21 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patch_notifier", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="firstvisit",
            name="url",
        ),
    ]
