# Generated by Django 3.1.2 on 2021-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lockable_resource", "0003_lockableresource_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockableresource",
            name="in_maintenance",
            field=models.BooleanField(default=False),
        ),
    ]
