# Generated by Django 3.1.2 on 2021-04-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockable_resource', '0004_lockableresource_in_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockableresource',
            name='signoff',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True, unique=True),
        ),
    ]
