# Generated by Django 3.2.4 on 2022-03-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0013_auto_20210614_1032"),
        ("lockable_resource", "0006_lockableresource_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="lockableresource",
            name="associated_queue",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="rqueue.rqueue",
            ),
        ),
    ]
