# Generated by Django 3.1.2 on 2021-03-17 22:53

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rqueue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", jsonfield.fields.JSONField(default=dict)),
                ("priority", models.IntegerField()),
                ("time_requested", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
