# Generated by Django 3.1.2 on 2021-03-17 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rqueue",
            options={"verbose_name_plural": "Requests in Queue"},
        ),
        migrations.AlterField(
            model_name="rqueue",
            name="time_requested",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
