# Generated by Django 3.1.2 on 2021-03-18 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0003_auto_20210318_2246"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rqueue",
            name="priority",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
    ]
