# Generated by Django 3.1.2 on 2021-04-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rqueue', '0007_auto_20210324_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='rqueue',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('finished', 'finished'), ('failed', 'failed'), ('aborted', 'aborted')], default='pending', max_length=32),
        ),
    ]
