# Generated by Django 3.1.2 on 2021-04-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0008_rqueue_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rqueue",
            name="pended_time_descriptive",
            field=models.CharField(default=None, max_length=1024, null=True),
        ),
    ]
