# Generated by Django 3.1.2 on 2021-04-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rqueue', '0009_rqueue_pended_time_descriptive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rqueue',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED'), ('ABORTED', 'ABORTED')], default='PENDING', max_length=32),
        ),
    ]
