# Generated by Django 3.2.5 on 2022-05-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0013_auto_20210614_1032"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rqueue",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("ALMOST_FINISHED", "ALMOST_FINISHED"),
                    ("FINISHED", "FINISHED"),
                    ("FAILED", "FAILED"),
                    ("ABORTED", "ABORTED"),
                    ("INITIALIZING", "INITIALIZING"),
                ],
                default="INITIALIZING",
                max_length=32,
            ),
        ),
    ]
