# Generated by Django 3.1.2 on 2026-04-16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rqueue", "0015_alter_rqueue_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rqueue",
            name="priority",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
    ]
