
from django.urls import path, include
from . import views

# The routers module in Django Rest Framework provides a way 
# to automatically generate URL patterns for your API views. 
from rest_framework import routers

# # Create a router instance
router = routers.DefaultRouter()

# This is a method provided by the router instance to register a viewset with it.
# The first argument ('courses') specifies the base URL path for this viewset. 
# The second argument (views.CourseView) is the viewset class that will handle 
# the HTTP requests and responses for the 'courses' API. 
router.register('resource_hw', views.ResourceHWView)

# 'include(router.urls)' includes all the URLs generated by the router. 
# This will include URLs for actions like listing, creating, updating, and deleting courses
###########################################################################
# The empty string '' as the first argument means that these URLs will be included 
# at the root of your project's URL structure. 
urlpatterns = [
    path('',include(router.urls)),
]